name: continuous deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
      - name: Build App
        run: | 
              npm install
              npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
           target_branch: gh-pages
           build_dir: build
        env:
            GH_PAT: ${{ secrets.DBMS_UI_ACCESS_TOKEN }}    